name: CI GitHub Pages
on:
  pull_request:
    branches: [develop, main]
  push:
    branches: [develop, main]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Cache node_modules
        uses: actions/cache@v1
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-

      - name: Use NodeJS v14.18.1
        uses: actions/setup-node@v1
        with:
          node-version: 14.18.1

      - name: Install
        run: |
          npm ci --omit=dev --ignore-scripts
          npm run install:dependencies

      - name: Build
        run: |
          npm run build:all:dev
          npm run deploy

      - name: Upload /docs artifacts
        uses: actions/upload-artifact@v1
        with:
          name: docs
          path: docs
      
      - name: Create Release
        if: github.event_name == 'push' && github.ref == 'refs/heads/main'
        run: npx semantic-release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Deploy TEST
        if: github.event_name == 'push' && github.ref == 'refs/heads/develop'
        run: |
          echo "deploy to TEST scripts"
      
      - name: Deploy to STAGE
        if: github.event_name == 'push' && github.ref == 'refs/heads/release'
        run: |
          echo "deploy to STAGE scripts"

      - name: Deploy to PROD
        if: github.event_name == 'push' && github.ref == 'refs/heads/main'
        run: |
          echo "deploy to PROD scripts"

      - name: Deploy to GitHub Pages
        if: github.event_name == 'push' && github.ref == 'refs/heads/main'
        uses: JamesIves/github-pages-deploy-action@4.1.1
        with:
          branch: gh-pages
          folder: docs
